volumes:
  pgdata:
  redis_data:


networks:
  cc_network:
    driver: bridge

services:
  postgres:
    image: postgres:17.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cc_network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - cc_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../cicd/docker/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/srv/
    networks:
      - cc_network
    depends_on:
      - postgres
      - redis
    command: /bin/sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    # command:  /bin/sh -c "./manage.py migrate &&  uwsgi --master --http :8000 --module src.wsgi"

  telegram:
    container_name: telegram
    build:
      context: ./telegram
      dockerfile: ../cicd/docker/telegram/Dockerfile
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - telegram/.env
    volumes:
      - ./telegram:/srv/
    networks:
      - cc_network
    command: /bin/sh -c "python bot.py"