# Generated by Django 5.1.6 on 2025-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='telegramuser',
            constraint=models.CheckConstraint(condition=models.Q(('telegram_username__contains', '@'), _negated=True), name='tu_telegram_username_contains_at'),
        ),
    ]
