# Generated by Django 5.1.6 on 2025-03-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'Архивировано')], default='published', max_length=20, verbose_name='Статус')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Валюта')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь внесший изменения')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('archived', 'Архивировано')], default='published', max_length=20, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('offer_type', models.CharField(choices=[('buy', 'Куплю'), ('sell', 'Продам')], max_length=4, verbose_name='Тип предложения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Минимальный объем')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Максимальный объем')),
                ('rate', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='geo.city', verbose_name='Город')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='offers.currency', verbose_name='Валюта')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь внесший изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('-rate', '-created_at'),
                'indexes': [models.Index(fields=['user'], name='offers_offe_user_id_a05bfe_idx'), models.Index(fields=['city'], name='offers_offe_city_id_d460d1_idx'), models.Index(fields=['currency'], name='offers_offe_currenc_c0cc19_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_value__gte', models.F('min_value')), ('min_value__isnull', True), ('max_value__isnull', True), _connector='OR'), name='ofr_check_max_value_gte_min_value')],
            },
        ),
    ]
